services:
  # 1. Backend API ASP.NET Core 9
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: minimal_api_backend
    restart: always
    environment:
      ConnectionStrings__MySqlConnection: "Server=mysql_db;Database=mydb;Uid=root;Pwd=root_password;"
      ConnectionStrings__SqlServerConnection: "Server=sqlserver_db;Database=mydb;User Id=sa;Password=Password123!;TrustServerCertificate=True;"
    ports:
      - "5000:5000"

  # 2. Base de Datos MySQL 8
  mysql_db:
    image: mysql:8.0
    container_name: minimal_api_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: mydb
    ports:
      - "3306:3306"

  # 3. Base de Datos Microsoft SQL Server 2022
  sqlserver_db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: minimal_api_sqlserver
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Password123!"
    ports:
      - "1433:1433"

  # 4. phpMyAdmin (Gestor Web Visual para MySQL)
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: minimal_api_phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql_db
      MYSQL_ROOT_PASSWORD: root_password
    depends_on:
      - mysql_db

  # 5. CloudBeaver (Gestor Web Universal para SQL Server / MySQL)
  cloudbeaver:
    image: dbeaver/cloudbeaver:latest
    container_name: minimal_api_cloudbeaver
    restart: always
    ports:
      - "8978:8978"
    depends_on:
      - sqlserver_db
